name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest 

    env:
      Solution_Name: TODO.sln
      Project_Name: TODO

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add MSBuild to the PATH
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore NuGet packages
    - name: Restore NuGet packages
      run: nuget restore ${{ env.Solution_Name }}

    # Build the solution
    - name: Build
      run: msbuild ${{ env.Solution_Name }} /p:Configuration=${{ matrix.configuration }} /p:Platform="Any CPU"

    # Execute unit tests 
    # - name: Execute unit tests
    #   run: dotnet test TODO.sln --no-build --configuration ${{ matrix.configuration }}

    # Upload build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build-Artifacts-${{ matrix.configuration }}
        path: |
          TODO/bin/${{ matrix.configuration }}/net8.0-windows/
        if-no-files-found: warn