name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [Any CPU]

    runs-on: windows-latest 

    env:
      Solution_Name: TODO.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2


    # Build the solution
    - name: Build
      run: msbuild $env:Solution_Name /p:Configuration=${{ matrix.configuration }} /p:Platform="${{ matrix.platform }}"

    # Execute all unit tests in the solution (if any)
    - name: Execute unit tests
      run: dotnet test $env:Solution_Name --no-build --configuration $env:Configuration

    # Upload build artifacts (.exe and .dll)
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build Artifacts
        path: |
          bin\${{ matrix.configuration }}\net8.0-windows\TODO.exe
          bin\${{ matrix.configuration }}\net8.0-windows\TODO.dll
